package dev.aetherstudioz.android.support

import dev.aetherstudioz.android.support.tools.DebugKeystore
import dev.aetherstudioz.build.BuildGoal
import dev.aetherstudioz.build.BuildRequest
import dev.aetherstudioz.build.VariantSelector
import dev.aetherstudioz.build.engine.BuildCache
import dev.aetherstudioz.build.engine.SimpleTaskContext
import dev.aetherstudioz.build.engine.TaskExecutorImpl
import dev.aetherstudioz.model.BuildSystemId
import dev.aetherstudioz.model.FacetTemplate
import dev.aetherstudioz.model.ModuleId
import dev.aetherstudioz.model.ModuleType
import dev.aetherstudioz.model.SourceSetTemplate
import dev.aetherstudioz.model.FacetCodecRegistry
import dev.aetherstudioz.model.ModuleTypeRegistry
import dev.aetherstudioz.model.impl.ProjectModel
import dev.aetherstudioz.platform.PluginId
import dev.aetherstudioz.testkit.testEnv
import kotlinx.coroutines.runBlocking
import java.util.zip.ZipFile
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * The Android multi-module sample (`mobile → feature → logic`) generated by [SampleAndroidProject] builds
 * to a real signed APK. This is the Android counterpart to the Java sample's build test, and exercises the
 * whole pipeline on a realistic project: an `android-lib` with its own resource + decoupled `R`, cross-
 * module resource merge, and a transitive plain-Java dependency. Skipped when no Android SDK is installed.
 */
class SampleAndroidProjectTest {

    private object JavaLib : ModuleType {
        override val id = "java-lib"
        override val displayName = "Java Library"
        override fun defaultSourceSets(): List<SourceSetTemplate> = emptyList()
        override fun defaultFacets(): List<FacetTemplate> = emptyList()
        override fun supportedBuildSystems(): Set<BuildSystemId> = setOf(BuildSystemId.NATIVE)
    }

    @Test
    fun theAndroidSampleBuildsToASignedApk() {
        val sdk = assumeAndroidSdk()

        testEnv("android-sample") { env ->
            val dir = env.dir
            val platform = env.platform
            val store = ProjectModel.open(dir, platform, FacetCodecRegistry().register(AndroidFacetCodec))
            val types = ModuleTypeRegistry(platform.extensions)
            types.register(JavaLib, PluginId("java-support"))
            AndroidSupport.register(types, FacetCodecRegistry())

            SampleAndroidProject.generate(store, types.resolve("android-app"), types.resolve("android-lib"), types.resolve("java-lib"))

            val signing = DebugKeystore.getOrCreate(dir.resolve(".keystore/debug.ks"), sdk.keytool)
            val buildSystem = AndroidBuildSystem.inProcess(sdk, signing)
            val project = store.workspace.projects.single { it.name == SampleAndroidProject.PROJECT }
            val graph = buildSystem.createBuildGraph(
                project, BuildRequest(listOf(ModuleId("app")), VariantSelector("debug"), BuildGoal.PACKAGE),
            )
            val log = StringBuilder()
            val outcome = runBlocking {
                TaskExecutorImpl(BuildCache(dir.resolve(".caches/build"))).execute(graph, SimpleTaskContext(log = { log.appendLine(it) }), 2)
            }
            assertTrue(outcome.succeeded, "android sample build failed:\n$log")

            val apk = dir.resolve("app/build/outputs/apk/debug/app-debug.apk")
            ZipFile(apk.toFile()).use { zf ->
                val entries = zf.entries().toList().map { it.name }.toSet()
                assertTrue("classes.dex" in entries && "resources.arsc" in entries, "incomplete APK: $entries")
                // all three modules' code dexed — native multidex splits the layers across classes*.dex.
                val dex = entries.filter { it.matches(Regex("classes\\d*\\.dex")) }
                    .joinToString(" ") { zf.getInputStream(zf.getEntry(it)).readBytes().toString(Charsets.ISO_8859_1) }
                assertTrue("Lcom/example/app/MainActivity;" in dex, "app not dexed")
                assertTrue("Lcom/example/feature/FeatureText;" in dex, "android-lib not dexed")
                assertTrue("Lcom/example/core/Calc;" in dex, "transitive java-lib not dexed")
                val arsc = zf.getInputStream(zf.getEntry("resources.arsc")).readBytes().toString(Charsets.ISO_8859_1)
                assertTrue("feature_title" in arsc && "app_name" in arsc, "resources not merged: arsc")
            }
        }
    }
}
